import { IMuscleData, ModelType, ModelTypeKey, Muscle } from '../types'

export const DEFAULT_MUSCLE_DATA: Record<Muscle, IMuscleData> = {
  trapezius: { exercises: [], frequency: 0 },
  'left-trapezius': { exercises: [], frequency: 0 },
  'right-trapezius': { exercises: [], frequency: 0 },
  'upper-back': { exercises: [], frequency: 0 },
  'left-upper-back': { exercises: [], frequency: 0 },
  'right-upper-back': { exercises: [], frequency: 0 },
  'lower-back': { exercises: [], frequency: 0 },
  'left-lower-back': { exercises: [], frequency: 0 },
  'right-lower-back': { exercises: [], frequency: 0 },
  chest: { exercises: [], frequency: 0 },
  'left-chest': { exercises: [], frequency: 0 },
  'right-chest': { exercises: [], frequency: 0 },
  biceps: { exercises: [], frequency: 0 },
  'left-biceps': { exercises: [], frequency: 0 },
  'right-biceps': { exercises: [], frequency: 0 },
  triceps: { exercises: [], frequency: 0 },
  'left-triceps': { exercises: [], frequency: 0 },
  'right-triceps': { exercises: [], frequency: 0 },
  forearm: { exercises: [], frequency: 0 },
  'left-forearm': { exercises: [], frequency: 0 },
  'right-forearm': { exercises: [], frequency: 0 },
  'back-deltoids': { exercises: [], frequency: 0 },
  'left-back-deltoids': { exercises: [], frequency: 0 },
  'right-back-deltoids': { exercises: [], frequency: 0 },
  'front-deltoids': { exercises: [], frequency: 0 },
  'left-front-deltoids': { exercises: [], frequency: 0 },
  'right-front-deltoids': { exercises: [], frequency: 0 },
  abs: { exercises: [], frequency: 0 },
  'left-abs': { exercises: [], frequency: 0 },
  'right-abs': { exercises: [], frequency: 0 },
  obliques: { exercises: [], frequency: 0 },
  'left-obliques': { exercises: [], frequency: 0 },
  'right-obliques': { exercises: [], frequency: 0 },
  adductor: { exercises: [], frequency: 0 },
  'left-adductor': { exercises: [], frequency: 0 },
  'right-adductor': { exercises: [], frequency: 0 },
  abductors: { exercises: [], frequency: 0 },
  'left-abductors': { exercises: [], frequency: 0 },
  'right-abductors': { exercises: [], frequency: 0 },
  hamstring: { exercises: [], frequency: 0 },
  'left-hamstring': { exercises: [], frequency: 0 },
  'right-hamstring': { exercises: [], frequency: 0 },
  quadriceps: { exercises: [], frequency: 0 },
  'left-quadriceps': { exercises: [], frequency: 0 },
  'right-quadriceps': { exercises: [], frequency: 0 },
  calves: { exercises: [], frequency: 0 },
  'left-calves': { exercises: [], frequency: 0 },
  'right-calves': { exercises: [], frequency: 0 },
  'left-shins': { exercises: [], frequency: 0 },
  'right-shins': { exercises: [], frequency: 0 },
  gluteal: { exercises: [], frequency: 0 },
  'left-gluteal': { exercises: [], frequency: 0 },
  'right-gluteal': { exercises: [], frequency: 0 },
  head: { exercises: [], frequency: 0 },
  neck: { exercises: [], frequency: 0 },
  'left-neck': { exercises: [], frequency: 0 },
  'right-neck': { exercises: [], frequency: 0 },
  knees: { exercises: [], frequency: 0 },
  'left-knees': { exercises: [], frequency: 0 },
  'right-knees': { exercises: [], frequency: 0 },
  'left-soleus': { exercises: [], frequency: 0 },
  'right-soleus': { exercises: [], frequency: 0 },
  ankles: { exercises: [], frequency: 0 },
  'left-ankle': { exercises: [], frequency: 0 },
  'right-ankle': { exercises: [], frequency: 0 }
}

export const DEFAULT_BODY_COLOR = '#B6BDC3'
export const DEFAULT_HIGHLIGHTED_COLORS = ['#81b1d9', '#277abf']
export const DEFAULT_MODEL_TYPE: ModelTypeKey = ModelType.ANTERIOR
